"""include restaurant

Revision ID: 9c9db9b52707
Revises:
Create Date: 2023-01-28 11:35:15.806145

"""
import geoalchemy2  # POSTGIS
import sqlalchemy as sa
import sqlmodel  # NEW

from alembic import op

# revision identifiers, used by Alembic.
revision = "9c9db9b52707"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("restaurants")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "restaurants",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("lat", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("lng", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="restaurants_pkey"),
    )
    # ### end Alembic commands ###
